"""Add profile fields to User

Revision ID: 26155648c031
Revises: 
Create Date: 2025-05-16 00:15:10.102050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26155648c031'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('field', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('video', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('industry', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('contact_person', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('contact_person')
        batch_op.drop_column('industry')
        batch_op.drop_column('company_name')
        batch_op.drop_column('video')
        batch_op.drop_column('skills')
        batch_op.drop_column('experience')
        batch_op.drop_column('field')
        batch_op.drop_column('fullname')

    # ### end Alembic commands ###
