"""Add profile fields to User

Revision ID: a3b5502b27b0
Revises: 26155648c031
Create Date: 2025-05-16 00:40:12.950649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b5502b27b0'
down_revision = '26155648c031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=150), nullable=True),
    sa.Column('field', sa.VARCHAR(length=100), nullable=True),
    sa.Column('experience', sa.TEXT(), nullable=True),
    sa.Column('skills', sa.VARCHAR(length=255), nullable=True),
    sa.Column('video', sa.VARCHAR(length=255), nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=150), nullable=True),
    sa.Column('industry', sa.VARCHAR(length=100), nullable=True),
    sa.Column('contact_person', sa.VARCHAR(length=150), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
